exclude: "^(whych/externs)"

# a curated list of available hooks
# https://pre-commit.com/hooks.html

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: no-commit-to-branch

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
        - id: remove-tabs
  - repo: https://github.com/life4/flakehell
    rev: v.0.8.0
    hooks:
      - id: flakehell
        additional_dependencies : ['flake8-bugbear==20.11.1']

  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
        additional_dependencies: ['toml==0.10.2']

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
      - id: mypy
