[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 80
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | whych/externs/*
)/
'''

[tool.coverage.run]
omit = ["setup.py", "whych/__main__.py", "whych/cli.py", "install_app.py", "whych/externs/*"]
