[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 80

[tool.isort]
profile = "black"
combine_as_imports = true

[tool.flakehell.plugins]
"flake8-bugbear" = ["+*"]

[tool.coverage.run]
omit = [
  "setup.py",
  "whych/__main__.py",
  "install_app.py",
  "whych/externs/*"
]
