steps:
- uses: actions/checkout@master
- uses: codecov/codecov-action@v1
  with:
    token: 834e486a-edd1-4bd2-a310-d527fde80d34
    file: ./coverage.xml
    flags: unittests
    name: codecov-umbrella
    fail_ci_if_error: true
